$(function () {
    layui.use(['layer', 'form','table'], function () {
        var layer = layui.layer
            , form = layui.form
            ,table = layui.table;

        /*layer.msg('Hello World');*/
        table.render({
            elem: '#test'
          /*  ,url:'/demo/table/user/'*/
            ,cellMinWidth: 80 //全局定义常规单元格的最小宽度，layui 2.2.1 新增
            ,cols: [[
                {field:'id', title: '编号', sort: true}
                ,{field:'filename',  title: '名称'}
                ,{field:'filedir',  title: '位置', sort: true}
                ,{field:'createtime',  title: '创建时间'}
                ,{field:'creator',  title: '创建人员'}
                ,{field:'accesscount',  title: '访问次数'}
                ,{field:'filesize',  title: '文件大小'}
                ,{field:'operate',  title: '操作'}
            ]]
            ,data: [{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
                },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            },{
                "id": "10001"
                ,"filename": "项目上线报告.doc"
                ,"filedir": "/upload/江苏农信/上线阶段"
                ,"createtime": "2019-09-10 20：00：00"
                ,"creator": "赵祖龙"
                ,"accesscount": "5"
                ,"filesize": "10kb"
            }]
            ,skin: 'line' //表格风格
            ,even: true
            ,page: true //是否显示分页
            ,limits: [5, 7, 10]
            ,limit: 10 //每页默认显示的数量
        });


    });


})